models/CategoriasAcreditaciones.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "categorias_acreditaciones".
 *
 * @property int $id
 * @property string $grupo
 *
 * @property AcreditacionesIndustriales[] $acreditacionesIndustriales
 * @property AcreditacionesInspectores[] $acreditacionesInspectores
 */
class CategoriasAcreditaciones  extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'categorias_acreditaciones';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['grupo'], 'required'],
            [['grupo'], 'string', 'max' => 100],
            [['grupo'], 'unique'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'grupo' => 'Grupo',
        ];
    }

    /**
     * Gets query for [[AcreditacionesIndustriales]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getAcreditacionesIndustriales()
    {
        return $this->hasMany(AcreditacionesIndustriales::className(), ['categoria' => 'id']);
    }

    /**
     * Gets query for [[AcreditacionesInspectores]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getAcreditacionesInspectores()
    {
        return $this->hasMany(AcreditacionesInspectores::className(), ['acreditacion' => 'id']);
    }

    /**
     * Funcion que devuelve TODAS las acreditaciones que no tiene el inspector.
     *
     * @author G-UX
     * @parameter  integer $id
     */
    public function getAcreditacionesFaltantes($id)
    {
        $result = Yii::$app->db
            ->createCommand()
            ->select('*')
            ->from('categorias_acreditaciones')
            ->where(
                'id NOT IN (SELECT acreditaciones_inspectores.acreditacion FROM  acreditaciones_inspectores WHERE inspector = :id)',
                [':id' => $id]
            )
            ->orderBy('categorias_acreditaciones.id')
            ->queryAll();

        return $result;
    }
}

controllers/CategoriasAcreditacionesController.php
<?php

namespace app\controllers;

use app\components\Traceador;
use app\models\AcreditacionesInspectores;
use app\models\CategoriasAcreditaciones;
use Exception;
use Yii;
use yii\web\Controller;
use yii\web\HttpException;
use yii\widgets\ActiveForm;

class CategoriasAcreditacionesController extends Controller
{


    //public $layout='main';

    /**
     * @return array action filters
     */
    public function filters()
    {
        return array(
            'accessControl', // perform access control for CRUD operations
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */

    public function accessRules()
    {
        Yii::$app->session['menu'] = 'estructura';
        Yii::$app->session['submenu'] = '';

        return array(
            array(
                'allow', // allow authenticated user to perform 'create' and 'update' actions
                'actions' => array('index', 'create', 'update', 'batchDelete'),
                'users' => array('@'),
            ),
            array(
                'deny',  // deny all users
                'users' => array('*'),
            ),
        );
    }

    public function actionIndex()
    {
        if (!\webvimark\modules\UserManagement\models\User::hasPermission('action_categoriasacreditaciones_index')) {
            throw new HttpException(401, 'Usted no tiene privilegios suficientes para realizar esta acción');
        }
        $data = CategoriasAcreditaciones::find()->orderBy('id')->all();
        Traceador::crearTraza('Acceso', 'Listado de Acreditaciones Industriales');
        return $this->render('index', array('data' => $data));
    }

    public function actionCreate()
    {
        if (!\webvimark\modules\UserManagement\models\User::hasPermission('action_categoriasacreditaciones_create')) {
            throw new HttpException(401, 'Usted no tiene privilegios suficientes para realizar esta acción');
        }
        $model = new CategoriasAcreditaciones();
        if (isset($_POST['CategoriasAcreditaciones'])) {
            $model->setAttributes($_POST['CategoriasAcreditaciones']);
            try {
                if ($model->save()) {
                    Traceador::crearTraza(
                        'creacion',
                        'Acreditación Industrial: ' . $model->grupo
                    );
                    Yii::$app->session->setFlash('success', 'Se adicionó un elemento exitosamente.');
                    if (isset($_GET['returnUrl'])) {
                        return $this->redirect($_GET['returnUrl']);
                    } else {
                        return $this->redirect(array('index'));
                    }
                }
            } catch (Exception $e) {
                $model->addError('id', $e->getMessage());
            }
        } elseif (isset($_GET['CategoriasAcreditaciones'])) {
            Yii::$app->session->setFlash('error', 'Ha ocurrido un error.');
            $model->attributes = $_GET['CategoriasAcreditaciones'];
        }
        return $this->render('create', array('model' => $model));
    }

    public function actionUpdate($id)
    {

        if (!\webvimark\modules\UserManagement\models\User::hasPermission('action_categoriasacreditaciones_update')) {
            throw new HttpException(401, 'Usted no tiene privilegios suficientes para realizar esta acción');
        }

        $model = $this->loadModel($id);

        if (isset($_POST['CategoriasAcreditaciones'])) {
            $model->setAttributes($_POST['CategoriasAcreditaciones']);
            try {
                if ($model->save()) {
                    Traceador::crearTraza(
                        'edicion',
                        'Acreditación Industrial: ' . $model->grupo
                    );
                    Yii::$app->session->setFlash('success', 'Se actualizó el elemento exitosamente.');
                    if (isset($_GET['returnUrl'])) {
                        return $this->redirect($_GET['returnUrl']);
                    } else {
                        return $this->redirect(array('index'));
                    }
                }
            } catch (Exception $e) {
                Yii::$app->session->setFlash('error', 'Ha ocurrido un error.');
                $model->addError('id', $e->getMessage());
            }
        }
        return $this->render('update', array('model' => $model));
    }

    public function loadModel($id)
    {
        $model = CategoriasAcreditaciones::findOne($id);
        if ($model === null)
            throw new HttpException(404, Yii::t('app', 'La página solicitada no existe.'));
        return $model;
    }

    /**
     * Performs the AJAX validation.
     * @param CModel the model to be validated
     */
    protected function performAjaxValidation($model)
    {
        if (isset($_POST['ajax']) && $_POST['ajax'] === 'categorias-acreditaciones-form') {
            echo ActiveForm::validate($model);
            Yii::$app->end();
        }
    }

    public function actionBatchDelete()
    {

        if (!\webvimark\modules\UserManagement\models\User::hasPermission('action_categoriasacreditaciones_batchdelete')) {
            throw new HttpException(401, 'Usted no tiene privilegios suficientes para realizar esta acción');
        }
        $successCount = 0;
        $request = Yii::$app->getRequest();
        if ($request->getIsPostRequest()) {
            if (isset($_POST['ids'])) {
                $ids = $_POST['ids'];
                foreach ($ids as $id) {
                    $model = $this->loadModel($id);
                    $ac = AcreditacionesInspectores::findAll('acreditacion = :a', array(':a' => $model->id));
                    if ($ac != null) {
                        Yii::$app->session->setFlash('error', 'Esta homologación tiene acreditaciones de inspectores asociadas y no puede ser eliminada');
                    } else {
                        try {
                            $model->delete();
                            $successCount++;
                            Traceador::crearTraza(
                                'eliminacion',
                                'Acreditación Industrial: ' . $model->grupo
                            );
                        } catch (Exception $e) {
                            Yii::$app->session->setFlash('error', 'No se han eliminado los elementos seleccionados: ' . $e->getMessage());
                            break;
                        }
                        Yii::$app->session->setFlash('success', 'Se han eliminado ' . $successCount . ' exitosamente');
                    }
                }
            }
        } else {
            throw new HttpException(400, 'Petición no válida');
        }
    }
}

views/categorias-acreditaciones/_form.php
<?php

use app\assets\SBAdminAsset;
use yii\bootstrap4\ActiveForm;
use yii\bootstrap4\Html;
use yii\helpers\Url;
?>
<div class="row">
    <div class="col-md-12">
        <div class="card border-left-primary shadow">
            <div class="card-header">
                <div class="caption"><i class="icon-reorder"></i>Acreditaciones Industriales</div>
                <div class="tools">
                    <a href="javascript:;" class="collapse"></a>
                    <a href="javascript:;" class="reload"></a>
                </div>
            </div>
            <div class="card-body form">
                <!-- BEGIN FORM-->
                <?php
                $form = ActiveForm::begin([
                    'id' => 'categorias-acreditaciones-form',
                    'enableAjaxValidation' => false,
                    'enableClientValidation' => true,
                ]);
                ?> <div class="container">
                    <?php echo Html::errorSummary($model);
                    ?>
                </div>
                <div class="form-body">

                    <div class="form-group">
                        <?php echo Html::activeLabel($model, 'grupo', array('class' => 'control-label')); ?>
                        <?php echo Html::activeTextInput($model, 'grupo', array('class' => 'form-control', 'placeholder' => 'Ej.: Homologación de buzos especialistas', 'maxlength' => 100)); ?>
                        <span class="help-block"><?php echo Html::error($model, 'grupo', array('class' => 'text-danger')); ?>
                        </span>
                    </div>

                </div>

                <div class="form-actions fluid">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="col-md-offset-3 col-md-9">
                                <button type="submit" class="btn btn-primary"><i class="icon-ok"></i> Guardar</button>
                                <a href="<?php echo Url::to('/categoriasacreditaciones/index') ?>" class="btn btn-default">Cancelar</a>
                            </div>
                        </div>
                    </div>
                </div>
                <?php ActiveForm::end() ?>
            </div>
            <!-- form -->
        </div>
    </div>
</div>


<?php


$this->registerCssFile('@web/plugins/bootstrap-fileupload/bootstrap-fileupload.css', Yii::$app->session->get('dependencias'));
$this->registerCssFile('@web/plugins/gritter/css/jquery.gritter.css', Yii::$app->session->get('dependencias'));
$this->registerCssFile('@web/plugins/select2/select2_metro.css', Yii::$app->session->get('dependencias'));
$this->registerCssFile('@web/plugins/clockface/css/clockface.css', Yii::$app->session->get('dependencias'));
$this->registerCssFile('@web/plugins/bootstrap-wysihtml5/bootstrap-wysihtml5.css', Yii::$app->session->get('dependencias'));
$this->registerCssFile('@web/plugins/bootstrap-datepicker/css/datepicker.css', Yii::$app->session->get('dependencias'));
$this->registerCssFile('@web/plugins/bootstrap-timepicker/compiled/timepicker.css', Yii::$app->session->get('dependencias'));
$this->registerCssFile('@web/plugins/bootstrap-colorpicker/css/colorpicker.css', Yii::$app->session->get('dependencias'));
$this->registerCssFile('@web/plugins/bootstrap-daterangepicker/daterangepicker-bs3.css', Yii::$app->session->get('dependencias'));
$this->registerCssFile('@web/plugins/bootstrap-datetimepicker/css/datetimepicker.css', Yii::$app->session->get('dependencias'));
$this->registerCssFile('@web/plugins/jquery-multi-select/css/multi-select.css', Yii::$app->session->get('dependencias'));
$this->registerCssFile('@web/plugins/bootstrap-switch/static/stylesheets/bootstrap-switch-metro.css', Yii::$app->session->get('dependencias'));
$this->registerCssFile('@web/plugins/jquery-tags-input/jquery.tagsinput.css', Yii::$app->session->get('dependencias'));
$this->registerCssFile('@web/plugins/bootstrap-markdown/css/bootstrap-markdown.min.css', Yii::$app->session->get('dependencias'));


$this->registerJsFile('@web/plugins/fuelux/js/spinner.min.js', Yii::$app->session->get('dependencias'));
$this->registerJsFile('@web/plugins/ckeditor/ckeditor.js', Yii::$app->session->get('dependencias'));
$this->registerJsFile('@web/plugins/bootstrap-fileupload/bootstrap-fileupload.js', Yii::$app->session->get('dependencias'));
$this->registerJsFile('@web/plugins/select2/select2.min.js', Yii::$app->session->get('dependencias'));
$this->registerJsFile('@web/plugins/bootstrap-wysihtml5/wysihtml5-0.3.0.js', Yii::$app->session->get('dependencias'));
$this->registerJsFile('@web/plugins/bootstrap-wysihtml5/bootstrap-wysihtml5.js', Yii::$app->session->get('dependencias'));
$this->registerJsFile('@web/plugins/bootstrap-datepicker/js/bootstrap-datepicker.js', Yii::$app->session->get('dependencias'));
$this->registerJsFile('@web/plugins/bootstrap-datetimepicker/js/bootstrap-datetimepicker.js', Yii::$app->session->get('dependencias'));
$this->registerJsFile('@web/plugins/clockface/js/clockface.js', Yii::$app->session->get('dependencias'));
$this->registerJsFile('@web/plugins/bootstrap-daterangepicker/moment.min.js', Yii::$app->session->get('dependencias'));
$this->registerJsFile('@web/plugins/bootstrap-daterangepicker/daterangepicker.js', Yii::$app->session->get('dependencias'));
$this->registerJsFile('@web/plugins/bootstrap-colorpicker/js/bootstrap-colorpicker.js', Yii::$app->session->get('dependencias'));
$this->registerJsFile('@web/plugins/bootstrap-timepicker/js/bootstrap-timepicker.js', Yii::$app->session->get('dependencias'));
$this->registerJsFile('@web/plugins/jquery-inputmask/jquery.inputmask.bundle.min.js', Yii::$app->session->get('dependencias'));
$this->registerJsFile('@web/plugins/jquery.input-ip-address-control-1.0.min.js', Yii::$app->session->get('dependencias'));
$this->registerJsFile('@web/plugins/jquery-multi-select/js/jquery.multi-select.js', Yii::$app->session->get('dependencias'));
$this->registerJsFile('@web/plugins/jquery-multi-select/js/jquery.quicksearch.js', Yii::$app->session->get('dependencias'));
$this->registerJsFile('@web/plugins/jquery.pwstrength.bootstrap/src/pwstrength.js', Yii::$app->session->get('dependencias'));
$this->registerJsFile('@web/plugins/bootstrap-switch/static/js/bootstrap-switch.min.js', Yii::$app->session->get('dependencias'));
$this->registerJsFile('@web/plugins/jquery-tags-input/jquery.tagsinput.min.js', Yii::$app->session->get('dependencias'));
$this->registerJsFile('@web/plugins/bootstrap-markdown/js/bootstrap-markdown.js', Yii::$app->session->get('dependencias'));
$this->registerJsFile('@web/plugins/bootstrap-maxlength/bootstrap-maxlength.min.js', Yii::$app->session->get('dependencias'));

$this->registerJsFile('@web/scripts/form-components.js', Yii::$app->session->get('dependencias'));





$js = <<<JS
 FormComponents.init();
JS;
$this->registerJs($js);
?>

views/categorias-acreditaciones/create.php
<?php

use yii\helpers\Url;
?>
<?php $this->beginBlock('block_titulo_pagina'); ?>
Acreditaciones Industriales
<small>Gesti&oacute;n de la informaci&oacute;n de Acreditaciones Industriales</small>
<?php $this->endBlock(); ?>

<?php $this->beginBlock('block_migas'); ?>
<a href="#"><i class="fa fa-briefcase"></i> Estructuras y Servicios</a>
<a href="<?php echo Url::to('/categorias-acreditaciones/index') ?>">Acreditaciones Industriales </a>
<a href="#">Nuevo </a>
<?php $this->endBlock(); ?>
<?php
echo $this->render('_form', array('model' => $model, 'buttons' => 'create'));
?>

views/categorias-acreditaciones/index.php
<?php

use app\assets\DataTablesAsset;
use yii\helpers\Html;
use yii\helpers\Url;
?>
<?php $this->beginBlock('block_titulo_pagina'); ?>
Acreditaciones Industriales
<small>Gesti&oacute;n de la informaci&oacute;n de Acreditaciones Industriales</small>
<?php $this->endBlock(); ?>

<?php $this->beginBlock('block_migas'); ?>
<a class="breadcumb-item" href="#"><i class="fa fa-briefcase"></i> Estructuras y Servicios - </a>
<a class="breadcumb-item active" href="#">Acreditaciones Industriales </a>
</li><?php $this->endBlock(); ?>

<?php if (Yii::$app->session->hasFlash('success')) { ?>
    <div class="alert alert-success alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
        <strong>&Eacute;xito!</strong>
        <?php echo Yii::$app->session->getFlash('success'); ?> </div>
<?php } else if (Yii::$app->session->hasFlash('error')) { ?>
    <div class="alert alert-danger alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
        <strong>Error</strong>
        <?php echo Yii::$app->session->getFlash('error'); ?> </div>
<?php } else if (Yii::$app->session->hasFlash('warning')) { ?>
    <div class="alert alert-warning alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
        <strong>Alerta!</strong>
        <?php echo Yii::$app->session->getFlash('warning'); ?> </div>
<?php } ?>
<br />
<div class="card border-left-primary shadow">
    <div class="card-header">
        <h3 class="card-title"><i class="fa fa-globe"></i>Gesti&oacute;n de Acreditaciones Industriales
        </h3>
    </div>
    <div class="card-body">
        <div class="table-toolbar">
            <div class="btn-group">
                <a href="<?php echo Url::to('/categorias-acreditaciones/create') ?>" class="btn btn-success">Nuevo
                    <i class="fa fa-plus"></i></a>
                <a id="eliminar" href="#" class="btn btn-danger">Eliminar seleccionados <i class="fa fa-trash"></i></a>
            </div>
        </div>
        <table class="table table-striped table-bordered table-hover" id="main_table">
            <thead>
                <tr>
                    <th class="table-checkbox">
                        <input id="select_all" type="checkbox" class="group-checkable" data-set="#sample_1 .checkboxes" />
                    </th>
                    <th> Acreditaci&oacute;n</th>
                    <th>
                        &nbsp;</th>
                </tr>
            </thead>
            <tbody>
                <?php
                foreach ($data as $value) {
                ?>
                    <tr class="odd gradeX">
                        <td><input type="checkbox" class="checkboxes" value="<?php echo $value->id ?>" /></td>
                        <td><?php echo $value->grupo ?></td>
                        <td>
                            <a href="<?php echo Url::to(['/categorias-acreditaciones/update', 'id' => $value->id]) ?>" class="btn btn-secondary btn-sm"><i class="fa fa-edit"></i> Editar</a>
                        </td>
                    </tr>
                <?php } ?>
            </tbody>
        </table>
    </div>
</div>
<?php
DataTablesAsset::register($this);

$js = <<<JS
    $(document).ready(function() {
        var table = $('#main_table').DataTable( {            
            lengthChange: false,
            buttons: [ 'copy', 'excel', 'pdf', 'colvis' ],
            
        } );    
        table
            .buttons()
            .container()
            .appendTo( '#main_table_wrapper .col-md-6:eq(0)' );
    } );
JS;
$this->registerJs($js); ?>

views/categorias-acreditaciones/update.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
?>
<?php $this->beginBlock('block_titulo_pagina'); ?>
Acreditaciones Industriales
<small>Gesti&oacute;n de la informaci&oacute;n de Acreditaciones Industriales</small>
<?php $this->endBlock(); ?>

<?php $this->beginBlock('block_migas'); ?>
<a class="breadcumb-item" href="#"><i class="fa fa-briefcase"></i> Estructuras y Servicios - </a>
<a class="breadcumb-item" href="<?php echo Url::to('/CategoriasAcreditaciones/index') ?>">Acreditaciones Industriales </a>
<span class="breadcumb-item active" href="#">Actualizar </span>
<?php $this->endBlock(); ?>
<?php
echo $this->render('_form', array('model' => $model));
?>