models/ProductosAcreditados.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "productos_acreditados".
 *
 * @property int $id
 * @property string|null $nombre
 * @property int|null $propietario
 * @property int|null $provincia
 * @property string|null $descripcion
 *
 * @property InspeccionesXProductos[] $inspeccionesXProductos
 * @property Entidades $propietario0
 * @property Provincias $provincia0
 * @property ShortcutHomologacionesProductos[] $shortcutHomologacionesProductos
 */
class ProductosAcreditados extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'productos_acreditados';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['propietario', 'provincia'], 'integer'],
            [['descripcion'], 'string'],
            [['nombre'], 'string', 'max' => 200],
            [['propietario'], 'exist', 'skipOnError' => true, 'targetClass' => Entidades::className(), 'targetAttribute' => ['propietario' => 'id']],
            [['provincia'], 'exist', 'skipOnError' => true, 'targetClass' => Provincias::className(), 'targetAttribute' => ['provincia' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nombre' => 'Nombre',
            'propietario' => 'Propietario',
            'provincia' => 'Provincia',
            'descripcion' => 'Descripcion',
        ];
    }

    /**
     * Gets query for [[InspeccionesXProductos]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getInspeccionesXProductos()
    {
        return $this->hasMany(InspeccionesXProductos::className(), ['producto' => 'id']);
    }

    /**
     * Gets query for [[Propietario0]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getPropietario0()
    {
        return $this->hasOne(Entidades::className(), ['id' => 'propietario']);
    }

    /**
     * Gets query for [[Provincia0]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getProvincia0()
    {
        return $this->hasOne(Provincias::className(), ['id' => 'provincia']);
    }

    /**
     * Gets query for [[ShortcutHomologacionesProductos]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getShortcutHomologacionesProductos()
    {
        return $this->hasMany(ShortcutHomologacionesProductos::className(), ['producto' => 'id']);
    }

    public function getFullID()
    {
        return $this->nombre .
            ' (' .
            $this->propietario0->nombre .
            ', ' .
            $this->provincia0->nombre .
            ') ';
    }
}

controllers/ProductosAcreditadosController.php
<?php

namespace app\controllers;

use app\components\CDbCriteria;
use app\components\Traceador;
use app\forms\BuscaObjetoForm;
use app\models\AprobacionXFuncionarios;
use app\models\Inspecciones;
use app\models\InspeccionesXProductos;
use app\models\ProductosAcreditados;
use app\models\ShortcutHomologacionesProductos;
use app\models\VisitasInspecciones;
use Exception;
use Yii;
use yii\data\Pagination;
use yii\web\Controller;
use yii\web\HttpException;
use yii\widgets\ActiveForm;

class ProductosAcreditadosController extends Controller
{
    //public $layout='main';

    /**
     * @return array action filters
     */
    public function filters()
    {
        return array(
            'accessControl', // perform access control for CRUD operations
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     *
     * @return array access control rules
     */
    public function accessRules()
    {
        Yii::$app->session['menu'] = 'objetoInspeccion';
        Yii::$app->session['submenu'] = 'productos';

        return array(
            array(
                'allow', // allow authenticated user to perform 'create' and 'update' actions
                'actions' => array('index', 'create', 'update', 'batchDelete', 'searchItems', 'historical'),
                'users' => array('@'),
            ),
            array(
                'deny',  // deny all users
                'users' => array('*'),
            ),
        );
    }

    public function actionIndex()
    {
        if (!\webvimark\modules\UserManagement\models\User::hasPermission('action_productosacreditados_index')) {
            throw new HttpException(401, 'Usted no tiene privilegios suficientes para realizar esta acción');
        }
        $form = new BuscaObjetoForm();
        if (isset($_POST['BuscaObjetoForm'])) {
            $form->setMyAttributes($_POST['BuscaObjetoForm']);
            $data = ProductosAcreditados::find();
        } else {
            $data = ProductosAcreditados::find();
        }
        $model = ProductosAcreditados::find();
        $countQuery = clone $model;
        $pages = new Pagination(['totalCount' => $countQuery->count()]);
        $pages->pageSize = 20;
        $data = $model->offset($pages->offset)
            ->limit($pages->limit)
            ->all();
        return $this->render('index', ['data' => $data, 'pages' => $pages, 'model' => $form]);
    }

    public function actionHistorical($id)
    {
        if (!\webvimark\modules\UserManagement\models\User::hasPermission('action_productosacreditados_historical')) {
            throw new HttpException(401, 'Usted no tiene privilegios suficientes para realizar esta acción');
        }

        //ToDo: revisar que el no de inspeccion coincida
        $data = $this->loadModel($id);
        $certificaciones = ShortcutHomologacionesProductos::findAll('producto = :p', array(':p' => $id));
        return $this->render('historico', array('data' => $data, 'certificaciones' => $certificaciones));
    }

    public function actionCreate()
    {
        if (!\webvimark\modules\UserManagement\models\User::hasPermission('action_productosacreditados_create')) {
            throw new HttpException(401, 'Usted no tiene privilegios suficientes para realizar esta acción');
        }
        $model = new ProductosAcreditados();
        if (isset($_POST['ProductosAcreditados'])) {
            $model->setAttributes($_POST['ProductosAcreditados']);

            if (isset($_POST['ProductosAcreditados']['propietario0'])) {
                $model->propietario0 = $_POST['ProductosAcreditados']['propietario0'];
            }
            if (isset($_POST['ProductosAcreditados']['provincia0'])) {
                $model->provincia0 = $_POST['ProductosAcreditados']['provincia0'];
            }

            try {
                if ($model->save()) {
                    Traceador::crearTraza('Creacion', 'Producto acreditado: ' . $model->nombre);
                    Yii::$app->session->setFlash('success', 'Se adicionó un elemento exitosamente.');
                    if (isset($_GET['returnUrl'])) {
                        return $this->redirect($_GET['returnUrl']);
                    } else {
                        return $this->redirect(array('index'));
                    }
                }
            } catch (Exception $e) {
                $model->addError('id', $e->getMessage());
            }
        } elseif (isset($_GET['ProductosAcreditados'])) {
            Yii::$app->session->setFlash('error', 'Ha ocurrido un error.');
            $model->attributes = $_GET['ProductosAcreditados'];
        }
        return $this->render('create', array('model' => $model));
    }

    public function actionUpdate($id)
    {
        if (!\webvimark\modules\UserManagement\models\User::hasPermission('action_productosacreditados_update')) {
            throw new HttpException(401, 'Usted no tiene privilegios suficientes para realizar esta acción');
        }
        $model = $this->loadModel($id);

        if (isset($_POST['ProductosAcreditados'])) {
            $model->setAttributes($_POST['ProductosAcreditados']);
            $model->propietario0 = $_POST['ProductosAcreditados']['propietario0'];
            $model->provincia0 = $_POST['ProductosAcreditados']['provincia0'];
            try {
                if ($model->save()) {
                    Traceador::crearTraza('Edicion', 'Producto acreditado: ' . $model->nombre);
                    Yii::$app->session->setFlash('success', 'Se actualizó el elemento exitosamente.');
                    if (isset($_GET['returnUrl'])) {
                        return $this->redirect($_GET['returnUrl']);
                    } else {
                        return $this->redirect(array('index'));
                    }
                }
            } catch (Exception $e) {
                Yii::$app->session->setFlash('error', 'Ha ocurrido un error.');
                $model->addError('id', $e->getMessage());
            }
        }
        return $this->render('update', array('model' => $model));
    }

    public function loadModel($id)
    {
        $model = ProductosAcreditados::findOne($id);
        if ($model === null) {
            throw new HttpException(404, Yii::t('app', 'La página solicitada no existe.'));
        }

        return $model;
    }

    /**
     * Performs the AJAX validation.
     *
     * @param CModel the model to be validated
     */
    protected function performAjaxValidation($model)
    {
        if (isset($_POST['ajax']) && $_POST['ajax'] === 'productos-acreditados-form') {
            echo ActiveForm::validate($model);
            Yii::$app->end();
        }
    }

    public function actionBatchDelete()
    {
        if (!\webvimark\modules\UserManagement\models\User::hasPermission('action_productosacreditados_batchdelete')) {
            throw new HttpException(401, 'Usted no tiene privilegios suficientes para realizar esta acción');
        }
        $successCount = 0;
        $band = false;
        $request = Yii::$app->getRequest();
        if ($request->getIsPostRequest()) {
            if (isset($_POST['ids'])) {
                $ids = $_POST['ids'];
                foreach ($ids as $id) {
                    $model = $this->loadModel($id);
                    try {
                        $tmpInsp = InspeccionesXProductos::findAll('producto = :mi', array(':mi' => $model->id));
                        if ($tmpInsp != null) {
                            foreach ($tmpInsp as $i) {
                                $tmpCertificados = ShortcutHomologacionesProductos::findAll('inspeccion = :insp', array(':insp' => $i->id));
                                if ($tmpCertificados != null) {
                                    foreach ($tmpCertificados as $certificado) {
                                        $certificado->delete();
                                    }
                                }

                                /*
                                 * Antes de borrar el elemento de Inspeccion por Producto debe comprobarse que no es el último de la
                                 * inspección padre y si lo es deben borrarse tanto la inspección como los elementos asociados
                                 * de visitas y aprobación por niveles
                                 */

                                $father = $i->inspeccion0->id;
                                $counter = InspeccionesXProductos::findAll('inspeccion = :f AND producto != :mi', array(':f' => $father, ':mi' => $model->id))->count();
                                if ($counter == 0) {
                                    $visitasAsoc = VisitasInspecciones::findAll('inspeccion = :f', array(':f' => $father));
                                    if ($visitasAsoc != null) {
                                        foreach ($visitasAsoc as $v) {
                                            $v->delete();
                                        }
                                    }
                                    $aprobaciones = AprobacionXFuncionarios::findAll('inspeccion = :f', array(':f' => $father));
                                    if ($aprobaciones != null) {
                                        foreach ($aprobaciones as $a) {
                                            $a->delete();
                                        }
                                    }
                                }
                                $i->delete();
                                Inspecciones::delete($father);
                            }
                        }
                        $model->delete();
                        Traceador::crearTraza(
                            'Eliminacion',
                            'Productos: ' . $model->nombre
                        );
                        ++$successCount;
                    } catch (Exception $e) {

views/productos-acreditados/_form.php
<?php

use app\assets\SBAdminAsset;
use app\models\Entidades;
use app\models\Provincias;
use yii\bootstrap4\ActiveForm;
use yii\bootstrap4\LinkPager;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\helpers\Url;
?>
<div class="row">
    <div class="col-md-12">
        <div class="card border-left-primary shadow">
            <div class="card-header">
                <div class="caption"><i class="icon-reorder"></i>Productos Acreditados</div>
                <div class="tools">
                    <a href="javascript:;" class="collapse"></a>
                    <a href="javascript:;" class="reload"></a>
                </div>
            </div>
            <div class="card-body form">
                <!-- BEGIN FORM-->
                <?php
                $form = ActiveForm::begin([
                    'id' => 'productos-acreditados-form',
                    'enableAjaxValidation' => false,
                    'enableClientValidation' => true,
                ]);
                ?> <div class="container">
                    <?php echo Html::errorSummary($model); ?>
                </div>
                <div class="form-body">

                    <div class="row">
                        <div class="col-md-12 col-sm-12">
                            <div class="form-group">
                                <?php echo Html::activeLabel($model, 'nombre', array('class' => 'control-label')); ?>
                                <?php echo Html::activeTextInput($model, 'nombre', array('id' => 'maxlength_alloptions', 'class' => 'form-control', 'placeholder' => 'nombre', 'maxlength' => 200)); ?>
                                <span class="help-block"><?php echo Html::error($model, 'nombre', array('class' => 'text-danger')); ?></span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6 col-sm-12">
                            <div class="form-group">
                                <?php echo Html::activeLabel($model, 'propietario', array('class' => 'control-label')); ?>
                                <?php echo Html::activeDropDownList($model, 'propietario0', ArrayHelper::map(Entidades::find()->all(), 'id', 'nombre'), array('class' => 'form-control input-xlarge select2me', 'data-placeholder' => 'Seleccione un elemento...')); ?>
                                <span class="help-block"><?php echo Html::error($model, 'propietario', array('class' => 'text-danger')); ?></span>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-12">
                            <div class="form-group">
                                <?php echo Html::activeLabel($model, 'provincia', array('class' => 'control-label')); ?>
                                <?php echo Html::activeDropDownList($model, 'provincia0', ArrayHelper::map(Provincias::find()->all(), 'id', 'nombre'), array('class' => 'form-control input-xlarge select2me', 'data-placeholder' => 'Seleccione un elemento...')); ?>
                                <span class="help-block"><?php echo Html::error($model, 'provincia', array('class' => 'text-danger')); ?></span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="form-group">
                                <?php echo Html::activeLabel($model, 'descripcion', array('class' => 'control-label')); ?>
                                <?php echo Html::activeTextArea($model, 'descripcion', array('class' => 'form-control', 'placeholder' => 'Descripción de las características del producto', 'maxlength' => 100)); ?>
                                <span class="help-block"><?php echo Html::error($model, 'descripcion', array('class' => 'text-danger')); ?></span>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="form-actions fluid">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="col-md-offset-3 col-md-9">
                                <button type="submit" class="btn btn-primary"><i class="icon-ok"></i> Guardar</button>
                                <a href="<?php echo Url::to('/productos-acreditados/index') ?>" class="btn btn-default">Cancelar</a>
                            </div>
                        </div>
                    </div>
                </div>
                <?php ActiveForm::end() ?>
            </div>
            <!-- form -->
        </div>
    </div>
</div>


<?php

$this->registerCssFile('@web/plugins/bootstrap-fileupload/bootstrap-fileupload.css', Yii::$app->session->get('dependencias'));
$this->registerCssFile('@web/plugins/gritter/css/jquery.gritter.css', Yii::$app->session->get('dependencias'));
$this->registerCssFile('@web/plugins/select2/select2_metro.css', Yii::$app->session->get('dependencias'));
$this->registerCssFile('@web/plugins/clockface/css/clockface.css', Yii::$app->session->get('dependencias'));
$this->registerCssFile('@web/plugins/bootstrap-wysihtml5/bootstrap-wysihtml5.css', Yii::$app->session->get('dependencias'));
$this->registerCssFile('@web/plugins/bootstrap-datepicker/css/datepicker.css', Yii::$app->session->get('dependencias'));
$this->registerCssFile('@web/plugins/bootstrap-timepicker/compiled/timepicker.css', Yii::$app->session->get('dependencias'));
$this->registerCssFile('@web/plugins/bootstrap-colorpicker/css/colorpicker.css', Yii::$app->session->get('dependencias'));
$this->registerCssFile('@web/plugins/bootstrap-daterangepicker/daterangepicker-bs3.css', Yii::$app->session->get('dependencias'));
$this->registerCssFile('@web/plugins/bootstrap-datetimepicker/css/datetimepicker.css', Yii::$app->session->get('dependencias'));
$this->registerCssFile('@web/plugins/jquery-multi-select/css/multi-select.css', Yii::$app->session->get('dependencias'));
$this->registerCssFile('@web/plugins/bootstrap-switch/static/stylesheets/bootstrap-switch-metro.css', Yii::$app->session->get('dependencias'));
$this->registerCssFile('@web/plugins/jquery-tags-input/jquery.tagsinput.css', Yii::$app->session->get('dependencias'));
$this->registerCssFile('@web/plugins/bootstrap-markdown/css/bootstrap-markdown.min.css', Yii::$app->session->get('dependencias'));

$this->registerJsFile('@web/plugins/fuelux/js/spinner.min.js', Yii::$app->session->get('dependencias'));
$this->registerJsFile('@web/plugins/ckeditor/ckeditor.js', Yii::$app->session->get('dependencias'));
$this->registerJsFile('@web/plugins/bootstrap-fileupload/bootstrap-fileupload.js', Yii::$app->session->get('dependencias'));
$this->registerJsFile('@web/plugins/select2/select2.min.js', Yii::$app->session->get('dependencias'));
$this->registerJsFile('@web/plugins/bootstrap-wysihtml5/wysihtml5-0.3.0.js', Yii::$app->session->get('dependencias'));
$this->registerJsFile('@web/plugins/bootstrap-wysihtml5/bootstrap-wysihtml5.js', Yii::$app->session->get('dependencias'));
$this->registerJsFile('@web/plugins/bootstrap-datepicker/js/bootstrap-datepicker.js', Yii::$app->session->get('dependencias'));
$this->registerJsFile('@web/plugins/bootstrap-datetimepicker/js/bootstrap-datetimepicker.js', Yii::$app->session->get('dependencias'));
$this->registerJsFile('@web/plugins/clockface/js/clockface.js', Yii::$app->session->get('dependencias'));
$this->registerJsFile('@web/plugins/bootstrap-daterangepicker/moment.min.js', Yii::$app->session->get('dependencias'));
$this->registerJsFile('@web/plugins/bootstrap-daterangepicker/daterangepicker.js', Yii::$app->session->get('dependencias'));
$this->registerJsFile('@web/plugins/bootstrap-colorpicker/js/bootstrap-colorpicker.js', Yii::$app->session->get('dependencias'));
$this->registerJsFile('@web/plugins/bootstrap-timepicker/js/bootstrap-timepicker.js', Yii::$app->session->get('dependencias'));
$this->registerJsFile('@web/plugins/jquery-inputmask/jquery.inputmask.bundle.min.js', Yii::$app->session->get('dependencias'));
$this->registerJsFile('@web/plugins/jquery.input-ip-address-control-1.0.min.js', Yii::$app->session->get('dependencias'));
$this->registerJsFile('@web/plugins/jquery-multi-select/js/jquery.multi-select.js', Yii::$app->session->get('dependencias'));
$this->registerJsFile('@web/plugins/jquery-multi-select/js/jquery.quicksearch.js', Yii::$app->session->get('dependencias'));
$this->registerJsFile('@web/plugins/jquery.pwstrength.bootstrap/src/pwstrength.js', Yii::$app->session->get('dependencias'));
$this->registerJsFile('@web/plugins/bootstrap-switch/static/js/bootstrap-switch.min.js', Yii::$app->session->get('dependencias'));
$this->registerJsFile('@web/plugins/jquery-tags-input/jquery.tagsinput.min.js', Yii::$app->session->get('dependencias'));
$this->registerJsFile('@web/plugins/bootstrap-markdown/js/bootstrap-markdown.js', Yii::$app->session->get('dependencias'));
$this->registerJsFile('@web/plugins/bootstrap-maxlength/bootstrap-maxlength.min.js', Yii::$app->session->get('dependencias'));

$this->registerJsFile('@web/scripts/form-components.js', Yii::$app->session->get('dependencias'));

$js = <<<JS
 FormComponents.init();
JS;
$this->registerJs($js);
?>

views/productos-acreditados/create.php
<?php

use yii\helpers\Url;

$this->title = 'Productos Acreditados';
$this->params['subtitle'] = 'Gesti&oacute;n de la informaci&oacute;n de Productos Acreditados';
$this->params['breadcrumbs'][] = [
    'label' => 'Objetos de Inspecci&oacute;n',
    'url' => ['personas-acreditadas/index'],
    'template' => '<i class="ti-receipt" i></i>&nbsp;{link}&nbsp;/&nbsp;'
];
$this->params['breadcrumbs'][] = [
    'label' => 'Productos',
    'url' => ['anuario/edicion'],
    'template' => '<i class="ti-receipt" i></i>&nbsp;{link}&nbsp;/&nbsp;'
];
$this->params['breadcrumbs'][] = 'Productos';
?>
?>
<?php $this->beginBlock('block_titulo_pagina'); ?>
Productos Acreditados <small>Gesti&oacute;n de la informaci&oacute;n de Productos Acreditados </small>
<?php $this->endBlock(); ?>

<?php $this->beginBlock('block_migas'); ?>
<li>
    <i class="fa fa-cogs"></i>
    <a href="#">Objetos de Inspecci&oacute;n</a>
    <i class="fa fa-angle-right"></i>
</li>
<li>
    <a href="<?php echo Url::to('/productos-acreditados/index') ?>">Productos </a>
    <i class="fa fa-angle-right"></i>
</li>
<li class="active">
    Nuevo
</li>

<?php $this->endBlock(); ?>
<?php
echo $this->render('_form', array('model' => $model, 'buttons' => 'create'));
?>

views/productos-acreditados/index.php
<?php

use app\assets\DataTablesAsset;
use app\models\Entidades;
use app\models\Provincias;
use yii\bootstrap4\ActiveForm;
use yii\bootstrap4\Html;
use yii\bootstrap4\LinkPager;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;

$this->title = 'Productos Acreditados';
$this->params['subtitle'] = 'Gesti&oacute;n de la informaci&oacute;n de Productos Acreditados';
$this->params['breadcrumbs'][] = [
    'label' => 'Objetos de Inspecci&oacute;n',
    'url' => ['personas-acreditadas/index'],
    'template' => '<i class="ti-receipt" i></i>&nbsp;{link}&nbsp;/&nbsp;'
];
$this->params['breadcrumbs'][] = 'Productos';
?>

<div class="card border-left-primary shadow">
    <div class="card-header">
        <h3 class="card-title">
            <i class="fa fa-search"></i> B&uacute;squeda avanzada
        </h3>
    </div>
    <div class="card-body">

        <?php $form = ActiveForm::begin(['options' => ['class' => 'form-inline'],]) ?>

        <div class="form-group mb-2">
            <?= $form->field($model, 'nombre', [
                'inputOptions' => ['class' => 'form-control mr-2']
            ])->textInput()->input('nombre', ['placeholder' => "Nombre"])->label(false); ?>
        </div>

        <div class="form-group mb-2">
            <?php echo $form->field($model, 'provincia', [
                'inputOptions' => ['class' => 'form-control mr-2']
            ])->dropdownList(
                ArrayHelper::map(Provincias::find()->all(), 'id', 'nombre'),
                ['style' => 'width:200px !important', 'prompt' => 'Seleccione una Provincia']
            )->label(false); ?>
        </div>

        <div class="form-group mb-2">
            <?php echo $form->field($model, 'propietario', [
                'inputOptions' => ['class' => 'form-control mr-2']
            ])->dropdownList(
                ArrayHelper::map(Entidades::find()->all(), 'id', 'nombre'),
                ['style' => 'width:200px !important', 'prompt' => 'Seleccione una Propietario']
            )->label(false); ?>
        </div>

        <?= Html::submitButton('Buscar', ['class' => 'btn btn-primary mb-2']) ?>

        <?php ActiveForm::end() ?>
    </div>
</div>
<!-- BEGIN EXAMPLE TABLE card-->
<div class="card border-left-primary shadow">
    <div class="card-header">
        <h6 class="card-title"><i class="fa fa-globe"></i>Gesti&oacute;n de Productos Acreditados</h6>
        <div class="card-subtitle">
            Mostrando <?= count($data) ?> de <?= $pages->pageCount ?> elementos
        </div>
    </div>
    <div class="card-body">
        <div class="table-toolbar">
            <div class="btn-group">
                <a href="<?php echo Url::to('/productos-acreditados/create') ?>" class="btn btn-success">Nuevo <i class="fa fa-plus"></i></a>
                <a id="eliminar" href="#" class="btn btn-danger">Eliminar seleccionados <i class="fa fa-trash"></i></a>
            </div>
            <div class="btn-group float-right">
                <div class="dataTables_paginate paging_bootstrap float-right">
                    <?php
                    echo LinkPager::widget([
                        'pagination' => $pages,
                    ]);
                    ?>
                </div>
            </div>
        </div>
        <table id="main_table" class="table table-striped table-bordered table-hover">
            <thead>
                <tr>
                    <th class="table-checkbox">
                        <input id="select_all" type="checkbox" class="group-checkable" data-set="#sample_1 .checkboxes" />
                    </th>
                    <th>Nombre</th>
                    <th>Propietario</th>
                    <th>Provincia</th>
                    <th>&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                <?php
                foreach ($data as $value) {
                ?>
                    <tr class="odd gradeX">
                        <td><input type="checkbox" class="checkboxes" value="<?php echo $value->id ?>" /></td>
                        <td><?php echo $value->nombre ?></td>
                        <td><?php echo $value->propietario0->nombre ?? '' ?></td>
                        <td><?php echo $value->provincia0->nombre ?? '' ?></td>
                        <td>
                            <a href="<?php echo Url::to(['/productos-acreditados/update', 'id' => $value->id]) ?>" class="btn btn-secondary btn-sm"><i class="fa fa-edit"></i> Editar</a>
                            &nbsp;
                            <a href="<?php echo Url::to(['/productos-acreditados/historical', 'id' => $value->id]) ?>" class="btn btn-success btn-sm"><i class="fa fa-edit"></i> Hist&oacute;rico</a>
                        </td>
                    </tr>
                <?php } ?>
            </tbody>
        </table>
        <hr />
        <div class="row">
            <div class="col-md-4 float-left">
                Mostrando <?= count($data) ?> de <?= $pages->pageCount ?> elementos
            </div>
            <div class="col-md-8">
                <div class="dataTables_paginate paging_bootstrap float-right">
                    <?php echo LinkPager::widget(['pagination' => $pages,]); ?>
                </div>
            </div>
        </div>
    </div>
</div>
<?php
DataTablesAsset::register($this);

$js = <<<JS
    $(document).ready(function() {
        var table = $('#main_table').DataTable( {            
            lengthChange: false,
            buttons: [ 'copy', 'excel', 'pdf', 'colvis' ],
            
        } );    
        table
            .buttons()
            .container()
            .appendTo( '#main_table_wrapper .col-md-6:eq(0)' );
    } );
JS;
$this->registerJs($js); ?>

views/productos-acreditados/update.php
<?php

use yii\helpers\Url;

?>
<?php $this->beginBlock('block_titulo_pagina'); ?>
Productos Acreditados <small>Gesti&oacute;n de la informaci&oacute;n de Productos Acreditados </small>
<?php $this->endBlock(); ?>

<?php $this->beginBlock('block_migas'); ?>
<a href="#"><i class="fa fa-cogs"></i>Objetos de Inspecci&oacute;n</a>
<li>
    <a href="<?php echo Url::to('/productos-acreditados/index') ?>">Productos </a>
    <i class="fa fa-angle-right"></i>
</li>
<li class="active">
    Actualizar
</li>

<?php $this->endBlock(); ?>
<?php
echo $this->render('_form', array('model' => $model));
?>